# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-01 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
